Java02. ДЗ 04, Чаркин Константин
kostya93/java_02 pull request #4
Opened 2016-10-14 15:48 UTC by kostya93

ftp

2016-11-02 19:16 UTC, jzuken requested changes

2016-11-02 19:16 UTC, jzuken commented on src/main/java/Client/ClientImpl.java
> +            return Status.NOT_OK;
ну то есть вы серьёзно считаете, что этого достаточно? и типа сказать не надо, почему именно и что конкретно не ок?

2016-11-02 19:16 UTC, jzuken commented on src/main/java/Server/ServerImpl.java
> +            if (type == 1) {
магические константы детектед

2016-11-02 19:16 UTC, jzuken commented on build.gradle
> +sourceCompatibility = 1.7
не компилится оно так, ссылки на методы в 1.8 появились

2016-11-02 19:16 UTC, jzuken commented on src/test/java/SimpleFtp/SimpleFtpTest.java
> +    public void testList() throws IOException {
хочется ещй тесты на несколько клиентов к одному серверу

2016-11-09 09:14 UTC, jzuken requested changes

2016-11-09 09:14 UTC, jzuken commented on src/main/java/SimpleFtp.java
> +    public static void main(String[] args) throws RootDirectoryNotFound, SocketIOException {
хочется CLI-интерфейс для сервера и клиента, чтобы можно было руками их подёргать

2016-11-14 15:08 UTC, jzuken requested changes

2016-11-14 15:08 UTC, jzuken commented on src/main/java/SimpleFtp.java
> +    private static void serverRepl() throws IOException, RootDirectoryNotFound {
клиента с сервером разносят по разным приложениям физически не потому, что так модно, а чтобы один от другого не зависел. сейчас же перекомпилировать всё придётся. давайте всё же разобьём на два приложения

2016-11-14 15:08 UTC, jzuken commented on src/main/java/SimpleFtp.java
> +        while (true) {
а как его завершить корректно?

2016-11-15 17:48 UTC, kostya93 commented on src/main/java/SimpleFtp.java
> +    private static void serverRepl() throws IOException, RootDirectoryNotFound {
@jzuken Вы хотите, чтобы это было 2 проекта или достаточно разнести по разным файлам ? В общем сейчас я сделал, что есть 2 класса `ClientRepl` и `ServerRepl` в обоих есть psvm методы, запуская `ClientRepl` запустится как ни странно клиент, `ServerRepl` - сервер. И один от другого не зависит.

2016-11-15 17:49 UTC, kostya93 commented on src/main/java/SimpleFtp.java
> +        while (true) {
@jzuken Сервер вроде завершается по команде `stop`. Если вы имели ввиду клиент, то добавил и там выход по `stop` .

2016-11-15 18:27 UTC, jzuken commented on src/main/java/SimpleFtp.java
> +        while (true) {
да, клиент

2016-11-15 18:27 UTC, jzuken commented on src/main/java/SimpleFtp.java
> +    private static void serverRepl() throws IOException, RootDirectoryNotFound {
да, я что-то такое и просил

2016-11-24 16:11 UTC, jzuken commented
если ввести несуществующий файл после get, то клиент зависает. фиговое у вас тестовое покрытие :)

2016-11-24 16:13 UTC, jzuken requested changes

2016-11-24 16:13 UTC, jzuken commented on src/test/java/SimpleFtp/SimpleFtpTest.java
> +    public void testList() throws IOException, RootDirectoryNotFound {
этот и предыдущий тест названиями поменялись походу

2016-11-24 16:13 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                            System.out.println(new String(content, StandardCharsets.UTF_8));
пусть он его на диск сохраняет лучше

2016-11-24 17:33 UTC, kostya93 commented on src/test/java/SimpleFtp/SimpleFtpTest.java
> +    public void testList() throws IOException, RootDirectoryNotFound {
fixed

2016-11-24 17:34 UTC, kostya93 commented on src/main/java/ClientRepl.java
> +                            System.out.println(new String(content, StandardCharsets.UTF_8));
добавил сохранение на диск (в текущую папку с именем как на сервере, если с таким же именем файл уже есть - перезаписывает его).

2016-11-24 17:35 UTC, kostya93 commented
get с несуществующим файлом исправил, добавил соответствующий тест.

2016-11-25 09:01 UTC, jzuken requested changes

2016-11-25 09:01 UTC, jzuken commented on src/test/java/SimpleFtp/SimpleFtpTest.java
> +        assertEquals("file", currentList.get(0).getName());
org.junit.ComparisonFailure: 
Expected :file
Actual   :folder

может стоит не по порядку, а просто по наличию проверять?

2016-11-25 09:37 UTC, kostya93 commented on src/test/java/SimpleFtp/SimpleFtpTest.java
> +        assertEquals("file", currentList.get(0).getName());
исправил.

2016-11-25 09:56 UTC, jzuken commented
ок, закрывайте. у меня доступа к репозиторию на запись нет

2016-11-25 10:01 UTC, closed without merging