Java02. ДЗ 05, Чаркин Константин
kostya93/java_02 pull request #5
Opened 2016-11-08 22:34 UTC by kostya93

2016-11-24 16:05 UTC, jzuken requested changes

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Torrent.java
> +    public static void main(String[] args) throws IOException, SerializationException {
оч хотелось бы получить реально два бинарника для торрента и клиента, чтобы можно было руками позапускать

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Tracker/TrackerImpl.java
> +        } catch (SocketException ignored) {
а почему он игнорится?

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Tracker/TrackerImpl.java
> +        } catch (IOException ignored) {
и тут тоже

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Client/FileSaver.java
> +        try(RandomAccessFile randomAccessFile = new RandomAccessFile(file, "r")){
пробел

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Client/FileSaver.java
> +        try(RandomAccessFile randomAccessFile = new RandomAccessFile(file, "rw")){
и тут

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Client/ClientImpl.java
> +    private Map<Integer, Set<PartOfFile>> fileIdToPartsOfFile = new HashMap<>();
я бы не советовал так называть имена переменных. читать их сложно, да и кодирование такое избыточно. просто fileParts было бы достаточно, на мой взгляд

2016-11-24 16:05 UTC, jzuken commented on src/main/java/Client/ClientImpl.java
> +    private Map<Integer, Set<PartOfFile>> fileIdToPartsOfFile = new HashMap<>();
и его, видимо, стоит final сделать, раз вы на нём лочитесь

2016-11-24 16:05 UTC, jzuken commented on src/test/java/TorrentTest.java
> +        client.executeUpload(SERVER_HOST, Tracker.PORT, someFile);
а проверить, что он правда закачался?

2016-11-24 16:05 UTC, jzuken commented on src/test/java/TorrentTest.java
> +public class TorrentTest {
тесты на STAT/GET?

2016-11-30 22:45 UTC, kostya93 commented on src/main/java/Torrent.java
> +    public static void main(String[] args) throws IOException, SerializationException {
Сделал как в домашке по ftp - 2 класса `ClietRepl` и `TrackerRepl`

2016-11-30 22:46 UTC, kostya93 commented on src/main/java/Tracker/TrackerImpl.java
> +        } catch (SocketException ignored) {
Потому что это штатный способ завершения программы, когда мы в главном потоке вызываем у сервера `stop()` , то в результате вызывается `serverSocket.close()` и уже в текущем потоке, `serverSocket.accept()` кидает `SocketException` мы его ловим и понимаем, что ничего, кроме завершения работы, делать не нужно. Если же произошло какое-то другое исключение (`IOException`), то сделать ничего разумного мы не можем, но хотя бы пишем `StackTrace`

2016-11-30 22:48 UTC, kostya93 commented on src/main/java/Tracker/TrackerImpl.java
> +        } catch (IOException ignored) {
тут добавил `printStackTrace`, что еще тут можно сделать - не очень понятно.

2016-11-30 22:49 UTC, kostya93 commented on src/main/java/Client/FileSaver.java
> +        try(RandomAccessFile randomAccessFile = new RandomAccessFile(file, "r")){
исправил.

2016-11-30 22:49 UTC, kostya93 commented on src/main/java/Client/FileSaver.java
> +        try(RandomAccessFile randomAccessFile = new RandomAccessFile(file, "rw")){
исправил.

2016-11-30 22:49 UTC, kostya93 commented on src/main/java/Client/ClientImpl.java
> +    private Map<Integer, Set<PartOfFile>> fileIdToPartsOfFile = new HashMap<>();
исправил.

2016-11-30 22:51 UTC, kostya93 commented on src/test/java/TorrentTest.java
> +public class TorrentTest {
Добавил тестов на stat/get/update/sources и сохранения состояния между перезапусками для сервера и для клиента.

2016-11-30 22:51 UTC, kostya93 commented on src/test/java/TorrentTest.java
> +        client.executeUpload(SERVER_HOST, Tracker.PORT, someFile);
исправил.

2016-12-02 21:36 UTC, kostya93 commented
Добавил возможность скачать файл целиком (раньше нужно было напрямую через метод get из API каждый `PartOfFile` качать) и добавил просмотр состояния скачиваемых файлов.

2016-12-16 08:57 UTC, jzuken requested changes

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                    if (serverPortStr.equals("")) {
а чего не isEmpty()?

2016-12-16 08:57 UTC, jzuken commented on build.gradle
> +group 'mit.spbau.ru'
хочется ещё, чтобы была возможность собрать полноценный jar со всеми зависимостями

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                    System.out.println("> 5 - STAT");
мне кажется, не стоит это каждый раз выводить

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                    System.out.println("> Enter currebt CLIENT_PORT(or nothing for 44444)");
опечатка

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                    System.out.println("> Enter SERVER_PORT(or nothing for \"localhost\")");
хост, видимо, а не порт

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                        case "0":
может тоже константы какие заведём? а то ну как-то страшно. и выделить этот кусок обработки ввода в отдельную функцию можно тоже

2016-12-16 08:57 UTC, jzuken commented on src/main/java/ClientRepl.java
> +                            System.out.println("> Inter absolute path to file");
inter?

2016-12-16 08:57 UTC, jzuken commented on src/main/java/Common/SharedFile.java
> +        return (int) (size % PartOfFile.MAX_SIZE == 0 ? size / PartOfFile.MAX_SIZE : size / PartOfFile.MAX_SIZE + 1);
а может size % PartOfFile.MAX_SIZE посчитать один раз всё-таки?

2016-12-16 08:57 UTC, jzuken commented on src/main/java/Tracker/TrackerImpl.java
> +        int  port = dataInputStream.readInt();
два пробела это перебор, видимо :)

2016-12-16 08:57 UTC, jzuken commented on src/test/java/TorrentTest.java
> +        tracker.start(SERVER_PORT, rootServer);
Common.SocketIOException: Cant create socket on port  = "55563";

	at Tracker.TrackerImpl.start(TrackerImpl.java:41)
	at TorrentTest.testStoreRestoreStateTracker(TorrentTest.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

2016-12-16 10:04 UTC, kostya93 commented
@jzuken 
Исправил.
Собрать jar можно командой `./gradlew all`
И в `build/libs` будут 2 файла `client-cli.jar` и `server-cli.jar`

2016-12-16 12:53 UTC, jzuken requested changes

2016-12-16 12:53 UTC, jzuken commented on src/test/java/TorrentTest.java
> +        tracker.start(SERVER_PORT, anotherRootServer);
теперь оно вот тут падает: 


Common.SocketIOException: Cant create socket on port  = "44454";

	at Client.ClientImpl.start(ClientImpl.java:52)
	at TorrentTest.testStoreRestoreStateClient(TorrentTest.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2016-12-16 12:53 UTC, jzuken commented
запустил два клиента, на одном добавил файл, на другом sources ничего не выдаёт:

> command LIST
Name = ".zshrc"; id = 0; size = 2235
> Enter COMMAND
> 
> 0 - EXIT
> 
> Commands to server:
> 1 - LIST
> 2 - UPLOAD
> 3 - SOURCES
> 4 - UPDATE
> 
> Commands to other client
> 5 - STAT
> 6 - GET
> 
> Other commands
> 7 - ADD FILE TO DOWNLOADING
> 8 - CHECK DOWNLOADING FILES STATE
> 3
> command SOURCES
> inter file id
0
> Enter COMMAND

2016-12-16 13:09 UTC, kostya93 commented
@jzuken тест пофиксил (вообще это непросто, с учетом того, что у меня все тесты проходят). Чтобы второй клиент увидел sources, первый после `UPLOAD` должен сделать `UPDATE` (такое API в задании описано)

2016-12-17 14:10 UTC, jzuken commented
так сделайте этот запрос, зачем вы эту задачу на пользователя перекладываете. в задании, кстати, указан только интерфейс общения трекера с клиентом, нигде не написано, каким должен быть пользовательский интерфейс. то, что вы решили сделать его таким же -- это ваше инженерное решение, и оно крайне неудачное. сделайте, пожалуйста, следующие команды в клиенте:
- посмотреть список файлов на трекере
- добавить файл на раздачу
- скачать файл 
- посмотреть статус закачек (я так понимаю, это пункт 8 у вас сейчас)

причём сейчас команда 7 ещё и размер какой-то спрашивает. зачем пользователю это знать? он хочет просто скачать файл по индексу

2016-12-17 14:11 UTC, jzuken requested changes

2016-12-17 14:11 UTC, jzuken commented on src/main/java/Client/Client.java
> +import javafx.stage.Stage;
это тут совсем не нужно, как мне кажется

2016-12-17 14:15 UTC, jzuken commented
тест, кстати, так и валится. судя по всему, клиент не успевает закрываться и отдать сокет нормально

2016-12-17 14:21 UTC, kostya93 commented
@jzuken Ну так раз не написано каким должен быть пользовательский интерфейс, значит я могу его делать каким захочу ?  И я сделал его таким, как мне удобно (удобство как раз в том, что он полностью дублирует API и удобно проверять что все работает как надо), этот интерфейс позволяет в полной мере проверить работоспособность программы, а появление новых требований 17 декабря, за 2 дня до зачетной недели, на которой у нас экзамен и 2 зачета в форме экзамена, это может быть и очень жизненно, но в рамках учебного процесса не очень хорошо.
Тем более, что есть следующее задание, в котором и надо сделать нормальный интерфейс.

2016-12-17 15:11 UTC, kostya93 commented
@jzuken 

---

Поменял поведение команд, теперь так:
- посмотреть список файлов на трекере - `1 - LIST`
- добавить файл на раздачу - `2 - UPLOAD`
- скачать файл - `7 - ADD FILE TO DOWNLOADING`
- посмотреть статус закачек (я так понимаю, это пункт 8 у вас сейчас) `8 - CHECK DOWNLOADING FILES STATE`

Остальные команды не убирал, если будут мешать - уберу.

---

> тест, кстати, так и валится. судя по всему, клиент не успевает закрываться и отдать сокет нормально

надеюсь теперь исправил

---

> это тут совсем не нужно, как мне кажется

исправил

---

2016-12-24 15:44 UTC, jzuken commented
> Ну так раз не написано каким должен быть пользовательский интерфейс, значит я могу его делать каким захочу ?

именно так. и классы вы проектируете тоже так, как вам хочется. а моя задача комментировать ваши решения так, чтобы вы чему-то учились. если вы думаете, что я придираюсь по каким-то другим причинам, это не так. просто зачесть вам все задачи с первого раза сэкономило бы мне целую кучу времени. 

а по поводу учебного процесса -- ну так если вы не делаете хорошо с первого раза, надо исправлять независимо от времени до зачёта

2016-12-24 15:44 UTC, jzuken commented
ладно, пусть будет так. закрывайте PR, у меня прав нет

2016-12-24 15:58 UTC, kostya93 commented
@jzuken 
> ну так если вы не делаете хорошо с первого раза, надо исправлять независимо от времени до зачёта

Эм, ну вы меня все равно не убедили, что интерфейс, предложенный вами в данном случае лучше. Всё-таки кажется, что суть этого задания в реализации правильного клиент/серверного взаимодействия, а юзер интерфейс сделан, что бы было проще убедиться в корректности работы, и тот интерфейс что был у меня - позволял это сделать. Но если вам хотелось видеть какой-то конкретный интерфейс (потому что понятия удобства тестирования через интерфейс у нас с вами могут различаться), то можно было указать это в задании.

> ладно, пусть будет так.

Этого вообще не понял, я же сделал именно так, как вы и просили (соответствие между тем, что вы просили и командами указано в сообщении выше) ? Или вас смущают лишние команды ?

2016-12-24 16:00 UTC, jzuken commented
не, это было к тому, что больше замечаний нет, закрываем задачу

2016-12-24 16:01 UTC, closed without merging